Repository Chandan2610/Solutions-Of-Daily-Leetcode-problems, pull requests merged in 2022-10, with the labels that each got.

#1 Merge branch 'main' of https://github.com/Chandan2610/Solutions-Of-Daily-Leetcode-problems
  Leetcode daily/5thOct.cpp
Labels: hactoberfest, hactoberfestaccepted

#2 6th October solution
  Leetcode daily/6th Oct.cpp
Labels: hactoberfest, hacktoberfest-accepted

#3 4th Oct solutions
  Leetcode daily/4th Oct.cpp
Labels: hactoberfest, hacktoberfest-accepted

#5 Create 2nd Oct.cpp
  Leetcode daily/2nd Oct.cpp
Labels: hactoberfest, hacktoberfest-accepted

#6 Create 1st oct.cpp
  Leetcode daily/1st oct.cpp
Labels: hactoberfest, hacktoberfest-accepted

#10 added 7th Oct soln
  Leetcode daily/7thOct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#12 added soln for 8thOct
  Leetcode daily/8thOct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#13 Create 11th Oct.cpp
  Leetcode daily/Chandan/11th Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create 9th oct.cpp
  Leetcode daily/9th oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#17 3rdOCT.cpp
  Leetcode daily/3rdOCT.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 Adding 14 oct leetcode challenge
  Leetcode daily/14_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#22 Adding 2 oct leetcode challenge
  Leetcode daily/2_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#24 Adding 1 oct leetcode challenge
  Leetcode daily/1_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added soln for 15Oct
  Leetcode daily/15Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#27 added soln of 16Oct
  Leetcode daily/16Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#29 17 Oct soln added
  Leetcode daily/17Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#32 Adding 14Oct.java
  Leetcode daily/14Oct.java
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added 20th-Oct.py
  Vivek-Goel/20th-Oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#36 Added 20_oct Leetcode Daily challenge solution
  Leetcode daily/20_Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#40 Added solution for today leetcode challenge
  Sahil-Saxena/22th_Oct.java
Labels: hacktoberfest, hacktoberfest-accepted

#41 Created name folder
  Leetcode daily/Purna/Ab.py
Labels: hacktoberfest, hacktoberfest-accepted

#43 Create 2Oct.cpp
  2Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 Create 3Oct.cpp
  3Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#46 Create 4Oct.cpp
  4Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#45 Oct 22 LeetCode Power question solution
  Leetcode daily/Sambit/oct22Power.cpp
  Leetcode daily/Sambit/oct22squareRoot.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#47 Skc Oct22.cpp
  Oct22.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#48 Skc Oct2.cpp
  Skc Oct2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#49 Revert "Oct 22 LeetCode Power question solution"
  Leetcode daily/Sambit/oct22Power.cpp
  Leetcode daily/Sambit/oct22squareRoot.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 Skc Oct3.cpp
  Skc Oct3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#58 Create Nitin oct 03
  Nitin oct 03
Labels: hacktoberfest, hacktoberfest-accepted

#51 Skc Oct4.cpp
  Skc Oct4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#59 22th_oct_solution.cpp
  Leetcode daily/Pranil/22th_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#57 RksOct4.cpp
  RksOct4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#52 Nitin oct o1
  Nitin oct o1
Labels: hacktoberfest, hacktoberfest-accepted

#53 Create RksOct.cpp
  RksOct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#55 Create RksOct2.cpp
  RksOct2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#56 RksOct3.cpp
  RksOct3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#54 Nitin oct 02
  Nitin oct 02
Labels: hacktoberfest, hacktoberfest-accepted

#61 21th_oct_solution.cpp
  Leetcode daily/Pranil/21th_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#62 20th_oct_solution.cpp
  Leetcode daily/Pranil/20th_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#60 8 october DPP
  Satyaijt/8oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 19th_oct_solution.cpp
  Leetcode daily/Pranil/19th_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#65 Create 11th_October.py
  Ansuman-Das/11th_October.py
Labels: hacktoberfest, hacktoberfest-accepted

#66 Create 23_October.py
  Shreyansh-Swain/23_October.py
Labels: hacktoberfest, hacktoberfest-accepted

#67 Created 01_Oct.py
  Sampad-Mohanty/01_Oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#68 Oct 23 Leetcode, Roman to Decimal solution
  Leetcode daily/Sambit/oct23RomanToInteger.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#69 oct23 Leetcode, Pallindrome problem solution
  Leetcode daily/Sambit/oct23Pallindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 Create 12-October.py
  Ansuman-Das/12-October.py
Labels: hacktoberfest, hacktoberfest-accepted

#72 Create 02_Oct.py
  Sampad-Mohanty/02_Oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#70 Create 18_October.py
  Shreyansh-Swain/18_October.py
Labels: hacktoberfest, hacktoberfest-accepted

#73 Create 13th-October.py
  Ansuman-Das/13th-October.py
Labels: hacktoberfest, hacktoberfest-accepted

#74 Create 03_Oct.py
  Sampad-Mohanty/03_Oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#77 Create 17_October.py
  Shreyansh-Swain/17_October.py
Labels: hacktoberfest, hacktoberfest-accepted

#76 Create 04_Oct.py
  Sampad-Mohanty/04_Oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#75 Create 14th-October.py
  Ansuman-Das/14th-October.py
Labels: hacktoberfest, hacktoberfest-accepted

#78 Create 10_October.py
  Shreyansh-Swain/10_October.py
Labels: hacktoberfest, hacktoberfest-accepted

#79 Create 16-Oct.cpp
  Biswadarshee_Behera/16-Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#80 Create 5-October.py
  Omm-Jyoti-Bai/5-October.py
Labels: hacktoberfest, hacktoberfest-accepted

#88 Create 15-Oct.cpp
  Biswadarshee_Behera/15-Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#96 Create 7-Oct.cpp
  Biswadarshee_Behera/7-Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#99 Create 8-October.py
  Omm-Jyoti-Bai/8-October.py
Labels: hacktoberfest, hacktoberfest-accepted

#100 Create 9-Oct.cpp
  Biswadarshee_Behera/9-Oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#102 Create 19-october.java
  Sandeep_Kumar_Patra/19-october.java
Labels: hacktoberfest, hacktoberfest-accepted

#103 Create 17_october.py
  sangram_jena/17_october.py
Labels: hacktoberfest, hacktoberfest-accepted

#105 Create 18-october.py
  M-Sambit/18-october.py
Labels: hacktoberfest, hacktoberfest-accepted

#104 23rd_oct.cpp
  Leetcode daily/Pranil/23rd_oct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#101 sqrt(x)
  Leetcode daily/Taufik/palindrome.cpp
  Leetcode daily/Taufik/plus-one.cpp
  Leetcode daily/Taufik/sqrt1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#107 Create cpp.cpp
  ananta/cpp.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#109 Create 29th oct
  Leetcode daily/29th oct
Labels: hacktoberfest, hacktoberfest-accepted

#110 Create 28th oct.py
  Leetcode daily/28th oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#112 Create 27th oct.py
  Leetcode daily/27th oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#113 Create 26th oct.py
  Leetcode daily/26th oct.py
Labels: hacktoberfest, hacktoberfest-accepted

#111 Create 29OCT.cpp
  Leetcode daily/29OCT.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#108 Create prog.cpp
  prodg.cpp
Labels: hacktoberfest, hacktoberfest-accepted
